//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class billet
{
    public int id { get; set; }
    public Nullable<int> place { get; set; }
    public Nullable<int> idfilm { get; set; }
    public Nullable<System.DateTime> date2 { get; set; }
}

public partial class film2
{
    public int id { get; set; }
    public string titre { get; set; }
    public string realisateur { get; set; }
    public string genre { get; set; }
    public string photo { get; set; }
}

public partial class users
{
    public int id { get; set; }
    public string nom { get; set; }
    public string login { get; set; }
    public string pass { get; set; }
    public string pays { get; set; }
    public string ville { get; set; }
}
